### ISSUE TITLE
With multiple repositories, no snapshot detail is shown

### ISSUE THREAD

**Issue by dsh** [ekutner/kopia-mon#11]
Freshly installed from git using Python 3.10 on Ubuntu. Happy to pass along any debug info you need.

When one repo is configured, I get the repository header and details on all snapshots. 

When multiple repositories are configured, I get just the repository headers and no snapshot details.

**Comment by dsh** [comment]
One repo configured

<img width="906" alt="Screenshot 2024-12-15 at 3 48 27 PM" src="https://github.com/user-attachments/assets/fa87a2a7-ebf3-49b2-a22c-1603e9b90897" />

**Comment by dsh** [comment]
Multiple repos configured

<img width="484" alt="Screenshot 2024-12-15 at 3 49 32 PM" src="https://github.com/user-attachments/assets/41c1d9ef-5615-4bc2-94f5-227351895709" />

**Comment by ekutner** [comment]
The program only shows details of new snapshots that were added since the last run. I'm guessing you ran it once with the single repository, which recorded that time as the last run, and then added the other two, but there were no snapshot taken since that run. If you run it again today you should see the snapshot details. If you still don't see it then delete the file called status.json created by the program and try again.

**Comment by ekutner** [comment]
There would now be a message saying there are no new snapshots since the last report in that scenario.

**Comment by dsh** [comment]
Thank you!
