### ISSUE TITLE
Snapshots should display the owner

### ISSUE THREAD

**Issue by dsh** [ekutner/kopia-mon#12]
I back up `/` from several machines to my main repository.

You can see in the output here that two `/` are shown, but there is no clue as to which machine they belong to.

Adding the owner to the snapshot will differentiate it. 

<img width="906" alt="Screenshot 2024-12-15 at 3 48 27 PM" src="https://github.com/user-attachments/assets/55f35ebf-8623-48ae-8c4d-34617bcbcc0a" />

**Comment by ekutner** [comment]
That's a good idea. Get the last version, it should now automatically add the host name if there is more than a single hostname in the repository.
For now the format I used is {hostname} : {path} but I'm wondering if {path}@{hostname} would be better. Thoughts?

**Comment by dsh** [comment]
I suggest `{user}@{host}:{path}` as that is what KopiaUI uses (note no spaces).

However, the new change is definitely better. And I love this project. It should be part of the main kopia distribution.

Your latest update brought in a Python 3.11 module `from typing import Self`. I was only Python 3.10 and had to upgrade.  There appears to be a backport for earlier Pythons: https://stackoverflow.com/a/77247460

**Comment by dsh** [comment]
Side idea: would be cool to provide a url prefix in config to create deep links for user@host or specific snapshots into the KopiaUI.

**Comment by ekutner** [comment]
I settled on {user}@{host} : {path} with spaces around the colon because on windows it's not very readable without the spaces.
The deep link idea is interesting but for it to work kopia-ui should register a handler for some custom URI protocol and intercept navigations. I don't know that it does something like that and don't have the time to research it so I'm going to pass on that.

**Comment by dsh** [comment]
No worries. Thank you very much for the great product and your responsiveness.
